services:
  dockeronment:
    build:
      context: .
      dockerfile: ECB_T8_T113.dockeronment
      args:
        DUID: ${DUID}
        DGID: ${DGID}
        DUSR: ${DUSR}
    volumes:
      - ${PWD}:${PWD}
    user: "${DUID}:${DGID}"
    working_dir: ${PWD}
    environment:
      - DUID=${DUID}
      - DGID=${DGID}
      - DUSR=${DUSR}

